-- TGT_D_CATEGORY definition
create or replace TABLE TGT_D_CATEGORY_LU (
	CATEGORY_KEY int AUTOINCREMENT,
	CATEGORY_ID NUMBER(38,0) NOT NULL,
	CATEGORY_DESC VARCHAR(16777216),
	ACTIVE_FLAG BOOLEAN DEFAULT TRUE,
	CREATED_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	unique (CATEGORY_ID),
	primary key (CATEGORY_KEY)
);


-- TGT_D_COUNTRY definition
create or replace TABLE TGT_D_COUNTRY_LU (
	COUNTRY_KEY int AUTOINCREMENT,
	COUNTRY_ID NUMBER(38,0) NOT NULL,
	COUNTRY_DESC VARCHAR(16777216),
	ACTIVE_FLAG BOOLEAN DEFAULT TRUE,
	CREATED_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	unique (COUNTRY_ID),
	primary key (COUNTRY_KEY)
);


-- TGT_D_CUSTOMER definition

create or replace TABLE TGT_D_CUSTOMER_B (
	CUSTOMER_KEY int AUTOINCREMENT,
	CUSTOMER_ID NUMBER(38,0) NOT NULL,
	FIRST_NAME VARCHAR(16777216),
	MIDDLE_NAME VARCHAR(16777216),
	LAST_NAME VARCHAR(16777216),
	ADDRESS VARCHAR(16777216),
	ACTIVE_FLAG BOOLEAN DEFAULT TRUE,
	CREATED_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	unique (CUSTOMER_ID),
	primary key (CUSTOMER_KEY)
);


-- TGT_D_REGION definition

create or replace TABLE TGT_D_REGION_LU (
	REGION_KEY int AUTOINCREMENT,
	REGION_ID NUMBER(38,0) NOT NULL,
	REGION_DESC VARCHAR(16777216),
	ACTIVE_FLAG BOOLEAN DEFAULT TRUE,
	CREATED_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	COUNTRY_KEY int,
	unique (REGION_ID),
	primary key (REGION_KEY),
	foreign key (COUNTRY_KEY) references TGT_D_COUNTRY_LU(COUNTRY_KEY)
);


-- TGT_D_STORE definition

create or replace TABLE TGT_D_STORE_B (
	STORE_KEY int AUTOINCREMENT,
	STORE_ID NUMBER(38,0) NOT NULL,
	STORE_DESC VARCHAR(16777216),
	ACTIVE_FLAG BOOLEAN DEFAULT TRUE,
	CREATED_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	REGION_KEY int,
	COUNTRY_KEY int,
	unique (STORE_ID),
	primary key (STORE_KEY),
	foreign key (REGION_KEY) references TGT_D_COUNTRY_LU(COUNTRY_KEY),
	foreign key (COUNTRY_KEY) references TGT_D_REGION_LU(REGION_KEY)
);


-- TGT_D_SUB_CATEGORY definition

create or replace TABLE TGT_D_SUB_CATEGORY_LU (
	SUBCATEGORY_KEY int AUTOINCREMENT,
	SUBCATEGORY_ID NUMBER(38,0) NOT NULL,
	SUBCATEGORY_DESC VARCHAR(16777216),
	ACTIVE_FLAG BOOLEAN DEFAULT TRUE,
	CREATED_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CATEGORY_KEY int,
	unique (SUBCATEGORY_ID),
	primary key (SUBCATEGORY_KEY),
	foreign key (CATEGORY_KEY) references TGT_D_CATEGORY_LU(CATEGORY_KEY)
);


-- TGT_D_PRODUCT definition

create or replace TABLE TGT_D_PRODUCT_B (
	PRODUCT_KEY int AUTOINCREMENT,
	PRODUCT_ID NUMBER(38,0) NOT NULL,
	PRODUCT_DESC VARCHAR(16777216),
	ACTIVE_FLAG BOOLEAN DEFAULT TRUE,
	CREATED_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CATEGORY_KEY int,
	SUBCATEGORY_KEY int,
	unique (PRODUCT_ID),
	primary key (PRODUCT_KEY),
	foreign key (CATEGORY_KEY) references TGT_D_CATEGORY_LU(CATEGORY_KEY),
	foreign key (SUBCATEGORY_KEY) references TGT_D_SUB_CATEGORY_LU(SUBCATEGORY_KEY)
);


-- TGT_F_TXN_AGG definition

create or replace TABLE TGT_F_TXN_AGG (
	TXN_AGG_KEY int AUTOINCREMENT,
	STORE_DESC varchar,
	MONTH_NAME VARCHAR,
	TOTAL_AMOUNT NUMBER(20,2),
	TOTAL_DISCOUNT NUMBER(20,2),
	TOTAL_QUANTITY NUMBER(20,2),
	CREATED_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (TXN_AGG_KEY)
--	foreign key (MONTH_KEY) references TGT_D_MONTH_B(MONTH_KEY)
);


-- TGT_F_TXN_B definition

create or replace TABLE TGT_F_TXN_B (
	TXN_KEY INT AUTOINCREMENT,
	TXN_ID NUMBER,
	TRANSACTION_TIME TIMESTAMP,
	QUANTITY NUMBER,
    AMOUNT NUMBER(20,2),
    DISCOUNT NUMBER(20,2),
	STORE_KEY int,
	CUSTOMER_KEY int,
	PRODUCT_KEY int,
	DAY_KEY int,
	CREATED_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	unique (TXN_ID),
	primary key (TXN_KEY),
	foreign key (STORE_KEY) references TGT_D_STORE_B(STORE_KEY),
	foreign key (CUSTOMER_KEY) references TGT_D_CUSTOMER_B(CUSTOMER_KEY),
	foreign key (PRODUCT_KEY) references TGT_D_PRODUCT_B(PRODUCT_KEY)
--	foreign key (DAY_KEY) references TGT_D_DAY(DAY_KEY)
);


